### ISSUE TITLE
latest Docker fails with exception

### ISSUE THREAD

**Issue by egonw** [cdk/depict#41]
Reproduce: `sudo docker run -p 9081:8080 simolecule/cdkdepict:1.9.2`

Expected: Depict website

Got:

```
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.setContentLengthLong(J)V
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1179)
```

Works fine with version 1.8

**Comment by johnmay** [comment]
Need to rebuild sorry, latest Spring needs Tomcat 8.5/9

**Comment by johnmay** [comment]
Have fixed, could you try again and close if all fixed. Decided didn't need a new release.

**Comment by egonw** [comment]
Yes, that seems to work. thanks!
